name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  package-chart:
    # The type of runner that the job will run on

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: package-chart
      - uses: azure/setup-helm@v1
        with:
          version: 'default' # default is latest stable
          id: install
      
      - name: Lint
        run: helm lint
        
      - name: package
        run: helm package
  test-chart: 
    steps: 
      - name: install
        run: helm install test test
        
      - name: test
        run: helm test test